<?php

// TRANSACTION TYPE

const TRANSACTION_REGISTER = 1;
const TRANSACTION_PAYMENT = 2;
const TRANSACTION_REFER_PAYMENT = 3;
const TRANSACTION_CHECKIN = 4;
const TRANSACTION_REDEEM = 5;
const TRANSACTION_TRANSFER = 6;
const TRANSACTION_GOOGLE_REVIEW = 7;
const TRANSACTION_FACEBOOK_REVIEW = 8;
const TRANSACTION_REFER_GIFT = 9;
const TRANSACTION_REGISTER_GIFT = 10;

// TRANSACTION STATUS

const TRANSACTION_PENDING = 1;
const TRANSACTION_ACCEPTED = 2;
const TRANSACTION_REJECTED = 3;
const TRANSACTION_PROCESSED = 4;
